export const dashboardSections = [
  {
    key: "about",
    label: "Tentang",
    path: "/dashboard/tentang",
    description: "Profil kelurahan",
  },
  {
    key: "heroSlides",
    label: "Hero",
    path: "/dashboard/hero",
    table: "hero_slides",
    title: "Hero Slides",
    description: "Atur konten slider utama.",
    fields: [
      { name: "title", label: "Judul", placeholder: "Judul slide" },
      { name: "description", label: "Deskripsi", type: "textarea", placeholder: "Deskripsi singkat" },
      { name: "cta_label", label: "Label Tombol", placeholder: "Baca Selengkapnya" },
      { name: "cta_href", label: "Tautan Tombol", placeholder: "#tentang" },
      { name: "sort_order", label: "Urutan", type: "number", helper: "Angka kecil muncul lebih dulu." },
    ],
  },
  {
    key: "featureCards",
    label: "Kartu",
    path: "/dashboard/kartu",
    table: "feature_cards",
    title: "Kartu Informasi",
    description: "Kelola highlight singkat pada bagian atas situs.",
    fields: [
      { name: "title", label: "Judul" },
      { name: "description", label: "Deskripsi", type: "textarea" },
      { name: "icon", label: "Emoji/Icon" },
      { name: "image_url", label: "URL Gambar", placeholder: "https://" },
      { name: "link_href", label: "Tautan", placeholder: "/layanan" },
      { name: "sort_order", label: "Urutan", type: "number" },
    ],
    imageFields: ["image_url"],
  },
  {
    key: "services",
    label: "Layanan",
    path: "/dashboard/layanan",
    table: "services",
    title: "Layanan",
    description: "Daftar layanan kelurahan.",
    fields: [
      { name: "title", label: "Judul" },
      { name: "description", label: "Deskripsi", type: "textarea" },
      { name: "icon", label: "Emoji/Icon" },
      { name: "sort_order", label: "Urutan", type: "number" },
    ],
    customComponent: "serviceMedia",
  },
  {
    key: "organization",
    label: "Organisasi",
    path: "/dashboard/organisasi",
    table: "organization_members",
    title: "Struktur Organisasi",
    description: "Atur data pejabat kelurahan.",
    fields: [
      { name: "name", label: "Nama" },
      { name: "role", label: "Jabatan" },
      { name: "nip", label: "NIP" },
      { name: "image_url", label: "Foto", placeholder: "https://" },
      { name: "sort_order", label: "Urutan", type: "number" },
    ],
    imageFields: ["image_url"],
  },
  {
    key: "galleryItems",
    label: "Galeri",
    path: "/dashboard/galeri",
    table: "gallery_items",
    title: "Galeri",
    description: "Unggah dokumentasi kegiatan.",
    fields: [
      { name: "title", label: "Judul" },
      { name: "caption", label: "Keterangan", type: "textarea" },
      {
        name: "cover_url",
        label: "Cover",
        placeholder: "https://",
        helper: "Cover akan muncul pada landing page.",
      },
      { name: "sort_order", label: "Urutan", type: "number" },
    ],
    imageFields: ["cover_url"],
    customComponent: "gallery",
  },
  {
    key: "dataGroups",
    label: "Data",
    path: "/dashboard/data",
    table: "data_groups",
    title: "Kelompok Data",
    description: "Daftar konten pada bagian Data.",
    fields: [
      { name: "title", label: "Judul" },
      {
        name: "items",
        label: "Entri Data",
        type: "dataPairs",
        helper: "Isi nama data dan keterangannya per baris. Simpanan akan otomatis mengikuti format tabel publik.",
      },
      { name: "sort_order", label: "Urutan", type: "number" },
    ],
  },
  {
    key: "wilayahInfo",
    label: "Wilayah",
    path: "/dashboard/wilayah",
    table: "wilayah_stats",
    title: "Statistik Wilayah",
    description: "Informasi ringkas wilayah.",
    fields: [
      { name: "label", label: "Label" },
      { name: "value", label: "Nilai" },
      { name: "description", label: "Keterangan", type: "textarea" },
      { name: "image_url", label: "Foto", placeholder: "https://" },
      { name: "sort_order", label: "Urutan", type: "number" },
    ],
    imageFields: ["image_url"],
    customComponent: "wilayahMap",
  },
  {
    key: "contactInfo",
    label: "Kontak",
    path: "/dashboard/kontak",
    table: "contact_info",
    title: "Kontak",
    description: "Informasi kontak resmi.",
    fields: [
      { name: "label", label: "Label" },
      { name: "value", label: "Nilai", type: "textarea" },
      { name: "sort_order", label: "Urutan", type: "number" },
    ],
  },
  {
    key: "news",
    label: "Berita",
    path: "/dashboard/berita",
    description: "Editor berita",
  },
]

export const sidebarGroups = [
  {
    title: "Konten Utama",
    keys: ["about", "heroSlides", "featureCards", "services", "organization", "galleryItems"],
  },
  {
    title: "Data & Informasi",
    keys: ["dataGroups", "wilayahInfo", "contactInfo"],
  },
  {
    title: "Publikasi",
    keys: ["news"],
  },
]
